[package]
name = "application"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
chrono = "0.4.41"
domain = { path = "../domain" }
thiserror = "2.0.12"
uuid = { version = "1.17.0", features = ["v4"] }
