[package]
name = "infrastructure"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
domain = { path = "../domain" }
sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "tls-native-tls",
    "mysql",
    "chrono",
] }
